branches:
  only:
  - main

services:
  - docker

# Pre-testing installs
install:
  - echo "nothing needs to be installed"

# Scripts to be run such as tests
before_script:
  - echo "no tests"

script:
  - docker build -t simple_graphql ./simple_graphql
  - docker build -t simple_mongo ./simple_mongo
  # Tagging
  - docker tag simple_mongo ludten/simple_graphql:v1
  - docker tag usimple_mongo ludten/simple_mongo:v1

# Push
after_success:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push ludten/simple_graphql:v1
  - docker push ludten/simple_mongo:v1
